// ============================================================
// RHYTHM
// What harmony.js is to pitch, this is to time. The circle of fifths is
// generated by adding 7 semitones mod 12 over and over; a Euclidean rhythm
// E(k, n) is generated by adding n/k steps mod n over and over, and produces
// the maximally even set — the same object on a different circle. E(3,8) is the
// tresillo, E(5,16) the bossa clave, E(8,12) the shuffle, and E(7,12) is the
// major scale itself. That is not a metaphor; it is the same arithmetic.
//
// So the half of a groove that keeps time is *generated*, because in every one
// of these traditions the timeline pattern genuinely is maximally even. The
// backbone — where the kick and snare land — is *authored*, because that is the
// style and there is no formula for it. tests/rhythm.test.mjs then holds the
// generated half against the definition and the authored half against its own
// invariants, with nothing checking itself.
//
// Like harmony.js this file imports nothing, on purpose: tests/load-module.mjs
// can only load a module that stands alone, and this is the half of the groove
// wheel worth checking in Node.
// ============================================================

// The parts the audio path can actually play. Held against the branches in
// js/play/loop.js by the test — an unhandled name there used to fall through to
// a silent 120 Hz tom rather than to an error.
export const KIT_PARTS = ['kick', 'snare', 'hihat', 'hihatOpen', 'tom1', 'tom2', 'floor', 'crash'];

// One character per step. A rest, a ghost note, a normal hit, an accent — the
// four dynamics a drummer plays and the reason a pattern here does not sound
// like a machine. A string is also the only format where the evenness is
// visible in the source: 'x--x--x-' reads as spread out, [0,3,6] does not.
export const STEP_CHARS = { '-': null, o: 0.42, x: 0.74, X: 1 };

// ============================================================
// EUCLIDEAN RHYTHM
// onset(i) = ceil(i * steps / onsets) places `onsets` hits as evenly as whole
// steps allow: every gap is floor(steps/onsets) or ceil(steps/onsets), so the
// gaps take at most two values and they differ by one. That *is* the definition
// of maximally even, so it needs no lookup table and no Bjorklund recursion.
//
// `rotation` turns the necklace, left by that many steps. The generated set
// always starts on a hit; a rotation is how the named patterns of a tradition
// are reached, since which hit a culture calls "one" is a choice the arithmetic
// does not make. E(5,8) rotated twice is the cinquillo; E(5,16) rotated ten
// times is the bossa clave; E(7,12) rotated seven times is the major scale.
// ============================================================
export function euclid(onsets, steps, rotation = 0) {
  const hits = new Array(steps).fill(false);
  if (!(onsets > 0) || !(steps > 0)) return hits;
  const count = Math.min(onsets, steps);
  const placed = new Array(steps).fill(false);
  for (let i = 0; i < count; i++) placed[Math.ceil((i * steps) / count)] = true;
  for (let i = 0; i < steps; i++) hits[i] = placed[(i + rotation % steps + steps) % steps];
  return hits;
}

export function euclidPattern(onsets, steps, rotation = 0) {
  return euclid(onsets, steps, rotation).map((hit) => (hit ? 'x' : '-')).join('');
}

/** '--o-X---' → [{ step: 2, vel: 0.42 }, { step: 4, vel: 1 }] */
export function parseStepPattern(text) {
  const hits = [];
  for (let step = 0; step < text.length; step++) {
    const vel = STEP_CHARS[text[step]];
    if (vel) hits.push({ step, vel });
  }
  return hits;
}

// ============================================================
// THE LIBRARY
// Twelve grooves, so the wheel's wedges are 30° and the chord wheel's geometry
// carries over unchanged. Four families of three, and both axes are position:
//
//   * The family boundaries land on 12 / 3 / 6 / 9 o'clock, which are also the
//     four beats of the bar on the ring inside — the two circles share their
//     heavy spokes instead of fighting over them.
//   * Clockwise inside a family is strictly busier. A wedge's position
//     therefore predicts what it will sound like, which is the whole reason the
//     layout is worth its corner of the screen.
//
// `beats` is how many pulses the steps group into. Every groove here is in
// four; the field exists so a 3/4 family is a data change rather than a
// rewrite, since the same twelve wedges regrouped is a genuinely interesting
// thing to watch happen.
//
// `timeline` declares which parts are generated and from what. The pattern
// strings below still spell those parts out, so the source shows the shape —
// the test holds the two against each other, which is what catches a hand edit
// that quietly breaks the evenness.
// ============================================================
export const GROOVE_FAMILIES = ['РІВНО', 'СВІНҐ', 'ЛАТИНА', 'ПОВІЛЬНО'];

export const GROOVES = [
  // ---- РІВНО — the sixteenth grid, beats on steps 0 4 8 12 ----
  {
    name: 'ПУЛЬС', family: 'РІВНО', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 4, rotation: 0 }],
    parts: {
      hihat: 'x---x---x---x---',
      kick:  'X---------------',
      snare: '--------X-------',
    },
  },
  {
    name: 'РОК', family: 'РІВНО', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-x-x-x-x-x-x-x-',
      kick:  'X-------X-------',
      snare: '----X-------X---',
    },
  },
  {
    // Closed hat on the beat, open hat on the "and" — the one groove whose
    // sound *is* the pedal lifting, and the reason audio.hihat's open branch
    // stopped being unreachable.
    name: 'ДИСКО', family: 'РІВНО', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 4, rotation: 0 }],
    parts: {
      hihat:     'x---x---x---x---',
      hihatOpen: '--X---X---X---X-',
      kick:      'X---X---X---X---',
      snare:     '----X-------X---',
    },
  },

  // ---- СВІНҐ — the triplet grid, beats on steps 0 3 6 9 ----
  {
    // E(8,12) is the shuffle exactly, with no rotation: long-short, long-short.
    name: 'ШАФЛ', family: 'СВІНҐ', steps: 12, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-xx-xx-xx-x',
      kick:  'X-----X-----',
      snare: '---X-----X--',
    },
  },
  {
    name: 'БЛЮЗ', family: 'СВІНҐ', steps: 12, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-xx-xx-xx-x',
      kick:  'X----XX-----',
      snare: '---X-----X--',
    },
  },
  {
    // Feathered kick under the ride, snare comping off the beat.
    name: 'ДЖАЗ', family: 'СВІНҐ', steps: 12, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-xx-xx-xx-x',
      kick:  'X--o--X--o--',
      snare: '--o--X--o--X',
    },
  },

  // ---- ЛАТИНА ----
  {
    // The cross-stick line is E(5,16) turned ten steps: the bossa clave, which
    // is a Euclidean necklace and not a pattern anyone had to remember.
    name: 'БОСА', family: 'ЛАТИНА', steps: 16, beats: 4,
    timeline: [
      { part: 'hihat', onsets: 8, rotation: 0 },
      { part: 'snare', onsets: 5, rotation: 10 },
    ],
    parts: {
      hihat: 'x-x-x-x-x-x-x-x-',
      snare: 'X--x--x---x--x--',
      kick:  'X-------X-------',
    },
  },
  {
    name: 'РЕҐЕТОН', family: 'ЛАТИНА', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-x-x-x-x-x-x-x-',
      kick:  'X------XX------X',
      snare: '---X--X----X--X-',
    },
  },
  {
    name: 'САМБА', family: 'ЛАТИНА', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 12, rotation: 0 }],
    parts: {
      hihat: 'x-xxx-xxx-xxx-xx',
      kick:  'X---x-X-x---X-x-',
      snare: '--o---X---o---X-',
    },
  },

  // ---- ПОВІЛЬНО ----
  {
    name: 'БАЛАДА', family: 'ПОВІЛЬНО', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-x-x-x-x-x-x-x-',
      kick:  'X---------X-----',
      snare: '----X-------X---',
    },
  },
  {
    // Half-time: one backbeat instead of two, and the ghosts carry the rest.
    name: 'ТРІП-ХОП', family: 'ПОВІЛЬНО', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 8, rotation: 0 }],
    parts: {
      hihat: 'x-x-x-x-x-x-x-x-',
      kick:  'X------X--X-----',
      snare: '--o-----X--o----',
    },
  },
  {
    name: 'ХІП-ХОП', family: 'ПОВІЛЬНО', steps: 16, beats: 4,
    timeline: [{ part: 'hihat', onsets: 12, rotation: 0 }],
    parts: {
      hihat: 'x-xxx-xxx-xxx-xx',
      kick:  'X--X----X-X-----',
      snare: '----X--o----X-o-',
    },
  },
];

export const GROOVE_COUNT = GROOVES.length;

const wrapIndex = (index) => ((Math.trunc(index) % GROOVE_COUNT) + GROOVE_COUNT) % GROOVE_COUNT;
export const grooveAt = (index) => GROOVES[wrapIndex(index)];
export const stepGroove = (index, direction) => wrapIndex(index + Math.sign(direction));

/** Every hit in one bar, step-sorted so a scheduler can walk it forward. */
export function grooveHits(groove) {
  const hits = [];
  for (const part of Object.keys(groove.parts)) {
    for (const hit of parseStepPattern(groove.parts[part])) {
      hits.push({ step: hit.step, part, vel: hit.vel });
    }
  }
  hits.sort((a, b) => a.step - b.step);
  return hits;
}

export const grooveDensity = (groove) => grooveHits(groove).length;

// ============================================================
// TEMPO AND TIME
// ============================================================
export const TEMPO_MIN = 60;
export const TEMPO_MAX = 160;
export const TEMPO_STEP = 4;
export const TEMPO_DEFAULT = 92;

export function stepTempo(bpm, direction) {
  const next = Math.round(bpm / TEMPO_STEP) * TEMPO_STEP + Math.sign(direction) * TEMPO_STEP;
  return Math.max(TEMPO_MIN, Math.min(TEMPO_MAX, next));
}

export const barSeconds = (bpm, beats = 4) => (beats * 60) / bpm;
export const stepSeconds = (bpm, groove) => barSeconds(bpm, groove.beats) / groove.steps;
export const stepTime = (groove, bpm, bar, step) =>
  bar * barSeconds(bpm, groove.beats) + step * stepSeconds(bpm, groove);

/** Step 0 sits at 12 o'clock, like the tonic on the chord wheel. */
export const stepAngle = (step, steps) => (step / steps) * 360;

/**
 * How many whole bars a take of `seconds` meant. Rounds to nearest, not up: a
 * finger that lifts a hair early meant this bar, and ceiling would hand back a
 * bar of silence.
 */
export function barsForDuration(seconds, bpm, groove, maxSeconds) {
  const bar = barSeconds(bpm, groove.beats);
  const maxBars = Math.max(1, Math.floor(maxSeconds / bar));
  return Math.min(maxBars, Math.max(1, Math.round(seconds / bar)));
}

// ============================================================
// HOW HARD A HIT LANDS
// A drum hit is a tap, so there is no stroke speed to read the way a strum has
// one. What a tap does carry is *where on the head it landed* — centre loud,
// rim quiet, which is the one dynamic a fingertip can genuinely express — and,
// when the finger is dragging across the kit, how fast it is travelling.
// Never returns zero: a rim shot is quiet, not silent.
// ============================================================
export const DRUM_VEL_MIN = 0.34;

export function drumHitVelocity({ radiusFraction = 0, speedPxPerMs = null } = {}) {
  const place = Math.max(0, Math.min(1, radiusFraction));
  const byPlace = 1 - place * 0.55;
  const bySpeed = speedPxPerMs === null ? 1 : Math.min(1, 0.55 + speedPxPerMs * 0.6);
  return Math.max(DRUM_VEL_MIN, Math.min(1, byPlace * bySpeed));
}
